name: Path lister
on: 
  workflow_dispatch:
jobs:
  list:
    name: Path lister
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v1

      - name: Fetch action
        id: pl
        uses: MaxKret/Path-lister-action-master@main
        with:
          path: "."
          type: ""

      - name: Output results
        run: |
          echo "Found ${{ steps.pl.outputs.path_count }} :"
          for i in ${{ steps.pl.outputs.paths }}; do
          echo $i
          done
